Add underscore to unused variable
Error pop up when building 1.94.0
stderr:
error: unused variable: `index`
   --> packages/modules/Virtualization/guest/pvmfw/src/rollback.rs:171:13
    |
171 |             index,
    |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_index`
    |
    = note: `-D unused-variables` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_variables)]`

error: aborting due to 1 previous error

Flag: EXEMPT PURE_REFACTOR
Bug: b/489837104
Test: m rust
Change-Id: I8dc845a16a4245f3c1ab617fed47d442ad66ec15